# This is a basic workflow to help you get started with Actions

name: test-workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Node.js
      
     # - name: Install dependencies
     #   run: echo installed dependencies
        
     # - name: run tests before build
     #   run: echo ran tests before build
        
      - name: Build and push image to Azure Registry Container 
        run: Build and push image to Azure Registry Container

      - name: Deploy to Azure
        run: echo deployed to Azure

#note: to deploy multiple images to Azure, try using a multiline separator 
     
    
